### ISSUE TITLE
Name isn't supported when adding a new device

### ISSUE THREAD

**Issue by maladon** [tadpol/MuranoCLI#11]
When adding a new device it would be handy to be able to name the device too.

**Comment by tadpol** [comment]
This is unfortunately a non-trivial feature.  It requires using the [1P RPC API](http://docs.exosite.com/rpc/#update) to write the name.

**Comment by cdurante** [comment]
+1

**Comment by tadpol** [comment]
The new device system doesn't allow for naming devices.  This feature has been removed form the WebUI some time ago, and so won't be added here.
