### ISSUE TITLE
Prefer \n instead of \r\n, and ensure trailing \n

### ISSUE THREAD

**Issue by anthonyrisinger** [tadpol/MuranoCLI#20]
`\n` is the standard EOL marker in Linux and OSX (years ago it was `\r` for OSX but not anymore). Even Windows honors this, though it still prefers `\r\n` when creating.

`mr` should write out `\n` EOL markers, and also ensure a trailing `\n` to make it a standard text file.

**Comment by anthonyrisinger** [comment]
`mr syncdown --endpoints` is the command being ran.

**Comment by tadpol** [comment]
sync down blindly copies what ever was saved into Murano previously.  So if you are seeing \r\n, someone uploaded that.

**Comment by anthonyrisinger** [comment]
Murano is adding it then I think because my editor won't even allow me to
write the text files in the way they're being copied down.

Currently all handlers are \r\n with NO trailing \r\n which isn't even
valid on Windows.

I'll check it out further and update.

**Comment by tadpol** [comment]
Huh. Well, if that's true we can certainly look into adding support for newline translations.

**Comment by akiratsai** [comment]
@anthonyrisinger This issue usually solved by Git when you commit or EditorConfig supported in your editor, otherwise we can detect the OS and replace EOL after `syncdown`, but it seems overhead to me, what do you think?

**Comment by anthonyrisinger** [comment]
@akiratsai Yeah I think that would be too much to ask of the user. `\n` is universal and should be OK to transform.

The thing I care most about is the trailing `\n`. Traditionally text files are required to end with a newline to be properly formatted, and even git will warn you (diff against files with no final newline say `\ No newline at end of file`). Since my editor will not create files without a trailing `\n`, something in the pipeline is calling `.strip()` and also converting the file to DOS format, ie. transforming `\n` -> `\r\n`.

My suggestion for this ticket would be to do one or all of:

* Warn the user whenever a script file does not end with `\n`. This is valid for both DOS (`\r\n`) and Unix files (`\n`).
* Use Unix everywhere and let the user know which files have been altered.
* Let the user decide how to handle it with a git-like `core.eol` option.
* Set `core.eol` according to the user's OS.
* Warn the user whenever a script file does not match `core.eol`.

I don't actually care too much about `\r\n` vs `\n`, so I won't be heartbroken if `core.eol` shows up, but I think it's better to normalize. `\n` is valid everywhere and can occasionally avoid some corner case problems. I definitely want whoever is stripping the final newline to stop though, because that confuses my editor slightly, is a little more annoying to `cat` out, and is non-standard.

**Comment by akiratsai** [comment]
@anthonyrisinger well done, learned from you, thanks.

**Comment by anthonyrisinger** [comment]
Was this fixed? I think it's likely not an issue with this code, but I can create an internal ticket if it's still a thing.

**Comment by tadpol** [comment]
Not sure. @landonb would know.

**Comment by anthonyrisinger** [comment]
@lbouma the gist here is:

1. Write things.
2. **All sane editors** will add a trailing `\n` (or `\r\n`).
3. `syncup` to Murano.
4. `syncdown` from Murano.
5. `\n` is changed to `\r\n` everywhere and trailing `\n` is stripped.

Seems like something in Murano proper would cause this, if this code base does zero transformations, but I don't have anything set up ATM to try. I saw this behavior during a hackathon quite some time ago.

**Comment by landonb** [comment]
@anthonyrisinger I tested and did not see this behavior. Newlines were preserved as `\n`, and the trailing newline was not removed. `hexdump` shows no diff.

**Comment by anthonyrisinger** [comment]
WINNING! Must have been fixed I guess inside a different component :+1:
